name: safety_island_bridge
topics:
  vehicle/driving_command:
    type: visionpilot_msgs/msg/DrivingCommand
    from_domain: 1
    to_domain: 2
  vehicle/status/steering_status:
    type: autoware_vehicle_msgs/msg/SteeringReport
    from_domain: 1
    to_domain: 2
  planning/scenario_planning/trajectory:
    type: autoware_planning_msgs/msg/Trajectory
    from_domain: 1
    to_domain: 2
  planning/visionpilot/trajectory_candidate:
    type: safety_island_msgs/msg/TrajectoryCandidate
    from_domain: 1
    to_domain: 2
  system/operation_mode/state:
    type: autoware_adapi_v1_msgs/msg/OperationModeState
    from_domain: 1
    to_domain: 2
  localization/kinematic_state:
    type: nav_msgs/msg/Odometry
    from_domain: 1
    to_domain: 2
  localization/acceleration:
    type: geometry_msgs/msg/AccelWithCovarianceStamped
    from_domain: 1
    to_domain: 2
