source.mode             = ros2

source.v4l2_device      = /dev/video0
source.v4l2_fps         = 10

engine.provider     = cuda
engine.device_id    = 0
engine.cache_dir    = /tmp/visionpilot_trt_cache
engine.workspace_gb = 1.0

model.precision    = fp32

speed_limit      = 33.3
L                = 2.860

visualization_on = true

webrtc_on = true
webrtc_port = 8080

rrd_on  = false
rrd_log = visionpilot.rrd
